### ISSUE TITLE
💅 Styled-Components en Acción 💅 

### ISSUE THREAD

**Issue by CharlyManotas** [wdcba/charlas#3]
## Título  :loudspeaker:
💅 Styled-Components en Acción 💅 

## Descripción  :pencil2:
¿Por qué styled components? 
- beneficios
- desventajas
- todo lo que necesitas saber antes de escoger algún otro 

## Duración  :hourglass:
30m - 45m

## Sobre tí  :memo:
Soy Carlos Manotas desarrollador frontend en Frávega, experto en hacer ToDo list apps en cualquier framework de paso, trabajando a diario en el stack de react, jugando con Elm, suelto rimas los fines de semana cuando me quito el traje de desarrollador, ilustrador , soñador.

_Twitter:_ [@CarlosManotasV](https://twitter.com/CarlosManotasV)

_Sitio:_[https://github.com/CarlosManotas/react-github-battle](https://lostapp-e8ede.firebaseapp.com/)

## Recursos :books:
*Coloca todos los recursos con los que cuentas para tú charla, slides, archivo compartido, repositorio, enlace en youtube, sitio web etc.*

**Comment by Villanuevand** [comment]
¡Genial charla!   
Muchas gracias por participar ....
![aplauses](https://media.giphy.com/media/11uArCoB4fkRcQ/giphy.gif)
