### ISSUE TITLE
Microservicios y APIs con GraphQL

### ISSUE THREAD

**Issue by Jarlakxen** [wdcba/charlas#4]
## Título  :loudspeaker:
*Microservicios y APIs con GraphQL*

## Descripción  :pencil2:
La idea de esta charla es hablar sobre conceptos básicos de de GraphQL, y compartir nuestra experiencia, en Fravega, a la hora migrando APIs REST a GraphQL.

## Duración  :hourglass:
*20m - 30m

## Sobre tí  :memo:
*Soy Facundo Viale, full-stack developer desde hace varios años. Me apasionan las tecnológicas web, en especial React. Pero cuando me toca hacer cosas en back, Scala siempre es una de mis primeras opciones. Soy un gran promotor de la programación funcional. 
Actualmente trabajo en Fravega pero pase por varias empresas como Despegar, Medallia y Avenida*

_Twitter:_ [@Jarlakxen](https://twitter.com/Jarlakxen)
_GitHub:_[@Jarlakxen](https://github.com/Jarlakxen)
_LinkedIn:_[@Jarlakxen](https://www.linkedin.com/in/facundoviale/)

## Recursos :books:
* [graphql.org](http://graphql.org)

**Comment by Villanuevand** [comment]
¡Genial charla!   
Muchas gracias por participar ....
![aplauses](https://media.giphy.com/media/11uArCoB4fkRcQ/giphy.gif)
